version: "3.8"
services:
  django:
    build: 
      context: .
      dockerfile: ./compose/development/django/Dockerfile
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./src/server:/code
  db:
    image: postgres