# Generated by Django 3.2.4 on 2021-06-21 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time at which the task was created', verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date and time at which the task was last modified', verbose_name='Modified at')),
                ('name', models.CharField(max_length=255, verbose_name='Task to complete')),
                ('description', models.TextField(max_length=500, verbose_name='Description of the task')),
                ('is_complete', models.BooleanField(default=False, help_text='This property is used to distinguish from completed tasks', verbose_name='Is task complete?')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created', '-modified'),
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
