# Generated by Django 3.2.4 on 2021-06-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Date and time at which the taxt was completed', null=True, verbose_name='Completed at'),
        ),
    ]
